import { DashboardHeroIcons } from "@/components/svg-icons";

export const docs = [
  {
    id: "1",
    icon: DashboardHeroIcons.Dos,
    iconBackground: "#FFF2E9",
    titleKey: "documents_title",
    subtitleKey: "documents_subtitle",
    unitKey: "contents",
    generatedCount: 0,
  },
  {
    id: "2",
    icon: DashboardHeroIcons.Words,
    iconBackground: "#F3F0FF",
    titleKey: "words_title",
    subtitleKey: "words_subtitle",
    unitKey: "words",
    generatedCount: 0,
  },
  {
    id: "3",
    icon: DashboardHeroIcons.Images,
    iconBackground: "#EFF9FE",
    titleKey: "images_title",
    subtitleKey: "images_subtitle",
    unitKey: "images",
    generatedCount: 0,
  },
  {
    id: "4",
    icon: DashboardHeroIcons.Codes,
    iconBackground: "#FFF2F5",
    titleKey: "codes_title",
    subtitleKey: "codes_subtitle",
    unitKey: "codes",
    generatedCount: 0,
  },
  {
    id: "5",
    icon: DashboardHeroIcons.Voice,
    iconBackground: "#F4FFE9",
    titleKey: "voiceover_title",
    subtitleKey: "voiceover_subtitle",
    unitKey: "tasks",
    generatedCount: 0,
  },
  {
    id: "6",
    icon: DashboardHeroIcons.Audio,
    iconBackground: "#F2EEFD",
    titleKey: "audio_title",
    subtitleKey: "audio_subtitle",
    unitKey: "audio_files",
    generatedCount: 0,
  },
] as const;
