import {
  TbBooks,
  TbCamera,
  TbCode,
  TbLanguage,
  TbLayoutDashboard,
  TbMessages,
  TbPdf,
  TbTextGrammar,
  TbWriting,
} from "react-icons/tb";

export const apps = [
  {
    id: "1",
    i18Key: "",
    title: "Dashboard",
    route: "/dashboard",
    Icon: TbLayoutDashboard,
  },
  {
    id: "2",
    i18Key: "",
    title: "Chat",
    route: "/chat",
    Icon: TbMessages,
  },
  {
    id: "3",
    i18Key: "",
    title: "Rewrite",
    route: "/rewrite",
    Icon: TbWriting,
  },
  {
    id: "4",
    i18Key: "",
    title: "Images",
    route: "/image",
    Icon: TbCamera,
  },
  {
    id: "5",
    i18Key: "",
    title: "Translate",
    route: "/translate",
    Icon: TbLanguage,
  },
  {
    id: "6",
    i18Key: "",
    title: "Grammar",
    route: "/grammar",
    Icon: TbTextGrammar,
  },
  {
    id: "7",
    i18Key: "",
    title: "Code",
    route: "/code",
    Icon: TbCode,
  },
  {
    id: "8",
    i18Key: "",
    title: "Prompt Library",
    route: "/template",
    Icon: TbBooks,
  },
  {
    id: "9",
    i18Key: "",
    title: "ChatPdf",
    route: "/chatpdf",
    Icon: TbPdf,
  },
] as const;
