export const signupQuestions = [
  {
    id: "1",
    key: "use",
    question: "What would you like to use Nerd Studio for?",
    options: ["Personal", "Work", "School", "Other"],
  },
  {
    id: "2",
    key: "people",
    question: "How many people will you be working with?",
    options: [
      "Just me",
      "2-10",
      "11-25",
      "26-50",
      "51-250",
      "251-500",
      "501+",
      "I don't know",
    ],
  },
  {
    id: "3",
    key: "solution",
    question: "Which solution would you like to start with? ",
    options: [
      "Finance & Accounting",
      "Creative & Design",
      "Personal Use",
      "Operations",
      "PMO",
      "Engineering & Product",
      "IT",
      "Support",
      "HR & Recruiting",
      "Sales & CRM",
      "Marketing",
      "Professional Services",
      "Other",
    ],
  },
  {
    id: "4",
    key: "find",
    question: "How did you hear about us",
    options: [
      "LinkedIn",
      "Billboard",
      "Search Engine (Google, Bing, etc.)",
      "TikTok",
      "YouTube",
      "Podcast / Radio",
      "TV / Streaming (Hulu, NBC, etc.)",
      "Facebook",
      "Instagram",
      "Friend / Colleague",
      "Other",
    ],
  },
] as const;
