name: Stage
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pulling ...
        uses: actions/checkout@v3
        with:
          clean: false
 
      - name: Build Docker Image
        run: docker build -t my-nextjs-app .
 
      - name: Run Docker Container
        run: docker run -p 3000:3000 my-nextjs-app
