name: Stage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pulling ...
        uses: actions/checkout@v3
        with:
          clean: false
      - name: Copy Project and Build
        run: |
          # Build the Docker image
          docker build -t nerd-studio-front .
          # Run the Docker container
          docker run -p 3000:3000 nerd-studio-front