name: Deploy Docker Container

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker container
        run: |
          docker compose -f docker/production/docker-compose.yml build
          docker compose -f docker/production/docker-compose.yml up -d
